### PR TITLE
Add Supervisor service support for non-Systemd platforms

### PR DESCRIPTION
**Pull request by RoboticCheese**
### Description

This is a first crack at supporting the otherwise-supported pre-Systemd platforms in the `hab_sup` resource. My init config fu was pretty atrophied, but things seem to function after cribbing bits and pieces from the chef-client and docker cookbooks.

The Upstart resource covers Ubuntu 14.04, CentOS 6, and Amazon Linux while the Sysvinit resource covers Debian 7 (at least, until support for Debian 7 is dropped).

All the `sup` suite's integration tests pass, in both Vagrant and Dokken.

### Issues Resolved

N/A (no existing GitHub issue)

### Check List

- [x] All tests pass. See <https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/TESTING.MD>
- [x] New functionality includes testing.
- [x] New functionality has been documented in the README if applicable
- [x] All commits have been signed for the Developer Certificate of Origin. See <https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/CONTRIBUTING.MD>

### CODE REVIEW

**Comment by RoboticCheese** [comment]
The build failures seem to be a few different things conspiring together:

- A couple of preexisting Cookstyle complaints. These are resolved.
- Intermittent 503s/504s pulling down packages in the `package` suite.
- Race condition starting up services before the supervisor's fully up. Added some more wait blocks that seem to help.
- Error loading toml in `resources/config.rb`. Something changed b/w ChefDK versions. 2.3.4 (chef 13.4.19) has the toml gem and 2.4.15 (chef 13.6.4) has tomlrb instead.

**Comment by jtimberman** [comment]
Hello @RoboticCheese, good to see you active here! 

Thank you for this pull request. I'm sorry no one replied sooner! We've merged some changes to fix our testing in Travis. Would you please rebase your branch and see if everything is passing now?

Thanks!
Joshua

**Comment by RoboticCheese** [comment]
It did have one successful build yesterday, but I found an embarrassing oversight this morning and kicked off a new one that then hit the acceptance 500 issue. :(

Just rebased to pull in #67. The build going now _should_ pass. 🤞 

Thanks!

**Comment by jtimberman** [comment]
Looks like we had a package installation hiccup. I reran the build and everything looks good!

**Pull request merged**
