### PR TITLE
Switch from toml gem to toml-rb gem for more robust parsing

### LINKED ISSUE #190: Switch from using the `toml` gem to using `toml-rb`
The toml gem is buggier and not maintained as well as some of the other options out there. For example it cannot parse:

`foo="bar"`
but it will parse:
`foo = "bar"`

This causes some unwanted behavior when applying configs.
I don't mind taking a crack at switching everything to `toml-rb`!

### PR DESCRIPTION
**Pull request by gscho**
### Description

Switches toml parsing gems from `toml` to `toml-rb`.

### Issues Resolved

#190 

### Check List

- [ ] All tests pass. See <https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/TESTING.MD>
- [ ] New functionality includes testing.
- [ ] New functionality has been documented in the README if applicable
- [ ] All commits have been signed for the Developer Certificate of Origin. See <https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/CONTRIBUTING.MD>

### CODE REVIEW

**Comment by tas50** [comment]
@gscho While I appreciate that you wrote this we really need to switch to the tomlrb gem, which is what Chef Infra Client is using. This allows us to run this cookbook without the need to install a gem dep at all. The state of toml in Ruby is sad. It should really just be a core library.

**Comment by gscho** [comment]
That sounds like a good idea to me. I'll refactor this PR to use that gem instead.

Would we want to include the gem still for backwards compatibility with chef 13/14?

**Comment by tas50** [comment]
It was introduced to the chef package in 13.7. I'd just makethe cookbook require Chef 13.7+

**Comment by gscho** [comment]
@tas50 is it this gem? https://github.com/fbernier/tomlrb?
Looks like there is no dumper implemented for writing a ruby hash to TOML (which is what we're doing here).

**Comment by jonlives** [comment]
I'm fine with changing the cookbook to require > Chef 13.7, fwiw :)

**Comment by tas50** [comment]
yeah if we need to bump to 13.7 then we bump to 13.7

**Comment by gscho** [comment]
@tas50 @jonlives Did you see my comment about the lack of a "dumper" function for the `tomlrb` gem?

**Comment by jonlives** [comment]
This is covered in #202  so closing this one in preference to that as it also contains other stuff that needs merging. Thanks for the PR!

**Pull request closed without merging**
