### PR TITLE
Allow local packages with service resource

### PR DESCRIPTION
**Pull request by Defilan**
### Description

This change allows a user to specify the bldr_url "local" in the service resource. This allows habitat to use local packages, such as those added with a tarball, to run.

### Issues Resolved

Allows local packages with the service resource

### Check List

- [x] All tests pass. See <https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/TESTING.MD>
- [x] New functionality includes testing.
- [x] New functionality has been documented in the README if applicable
- [x] All commits have been signed for the Developer Certificate of Origin. See <https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/CONTRIBUTING.MD>

### CODE REVIEW

**Comment by Defilan** [comment]
Let me know what you all think, I'm excited about getting this functionality added to the cookbook :)

**Comment by dayne** [comment]
This would be handy to have back again. 

We used this functionality back in hab 0.10 era and after upgrading to 0.50.3 found that habitat would only allow a local package to be installed if there was *no* package in bdlr.  Without ability to delete things off bdlr we found we were forced to manage our packages inside of bdlr instead of as a local repository.

**Comment by Defilan** [comment]
No longer needed

**Comment by jtimberman** [comment]
@Defilan Hey there, is this no longer needed? Or is it still needed?

**Comment by Defilan** [comment]
@jtimberman Yes, I still believe there is a need for this. As @dayne mentioned, this would help with packages that exist in bldr but where you want to run locally. It's not a destructive change, so it would be a simple fix.

**Pull request merged**
